
kraken_mem : 512
kraken_threads : 32
kraken_time: 12
build_time: 1

### Build
build_db_name : "kraken_db"
taxonomy: ""
fasta_extension: '.fasta.gz'
genome_folder: /home/kiesers/s/HumanUnifiedCatalog/gff/fasta



#### Mpping
# store one or several name : path
kraken_db:
  kraken_db : kraken_db
kraken_run_extra: "--gzip-compressed "
