
kraken_mem : 512000
kraken_threads : 32
kraken_time: 5 # 5 min
build_time: 30
braken_threads: 10
braken_mem: 20000

### Build
build_db_name : "kraken_db"
taxonomy: "green_genes_taxonomy.tsv"
genome_folder: /home/kiesers/s/HumanUnifiedCatalog/gff/fasta



#### Mpping


sample_table: "samples.tsv"

use_ramdisk: true  # copies kraken db to /dev/shm once, and runs all samples

# store one or several name : path
kraken_db:
  kraken_db : kraken_db
kraken_run_extra: "--gzip-compressed "
